### ISSUE TITLE
Unbound breakpoints

### ISSUE THREAD

**Issue by Haych** [sailpoint-oss/sp-connector-sdk-js#12]
Hi,

I am probably doing something wrong, but I am following the guide located here - https://developer.sailpoint.com/idn/docs/saas-connectivity/prerequisites - to create a new connector. I have updated my launch.json as per the page here - https://developer.sailpoint.com/idn/docs/saas-connectivity/in-depth/debugging#debug-through-the-vs-code-debug-configuration.

When I set a breakpoint and start debugging in VS Code the breakpoints are always unbounded. This was working last week so I am not sure what has changed? I can send requests to the running debug process via Postman, so that part if working.

I have uploaded my files, they havent been changed from the default values.

[package.json.txt](https://github.com/sailpoint-oss/sp-connector-sdk-js/files/10110574/package.json.txt)
[tsconfig.json.txt](https://github.com/sailpoint-oss/sp-connector-sdk-js/files/10110575/tsconfig.json.txt)
[launch.json.txt](https://github.com/sailpoint-oss/sp-connector-sdk-js/files/10110586/launch.json.txt)

Running VS Code 1.73.1
Node v16.18.1
NPM 9.1.2

**Comment by jordan-violet-sp** [comment]
@haych if this is still an issue, please resubmit.
